name: career_architect
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  http: ^1.2.2
  google_fonts: ^6.2.1
  flutter_dotenv: ^5.1.0
  flutter_markdown: ^0.7.3
  supabase_flutter: ^2.4.0
  google_generative_ai: ^0.4.7
  url_launcher: ^6.3.0
  pdf: ^3.11.1
  printing: ^5.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/logo.png
